---
- name: Verificar se o home do usuario ja foi copiado para o disco de dados
  stat:
    path: "{{ novo_home }}/{{ ansible_facts.env.SUDO_USER }}/.bashrc"
  register: home_usuario_copiado

- name: Copiar home do usuario para disco de dados
  synchronize:
    src: "/home/{{ ansible_facts.env.SUDO_USER }}"
    dest: "{{ novo_home }}/"
    archive: True
    rsync_opts:
      - "-X"
  delegate_to: "{{ inventory_hostname }}"
  when: not home_usuario_copiado.stat.exists

- name: Alterar home do usuario
  # feito via lineinfile porque o usermod nao funciona com usuarios conectados
  lineinfile:
    path: /etc/passwd
    backrefs: yes
    regexp: "^({{ ansible_facts.env.SUDO_USER }}:[^:]*:[0-9]+:[0-9]+:[^:]*):.+$"
    line: \g<1>:{{ novo_home }}/{{ ansible_facts.env.SUDO_USER }}:{{ shell_default }}
    state: present

- name: Aplicar context do SELinux
  shell:
    cmd: "semanage fcontext -a -e /home {{ mount_point_dados }}/home 2> >(grep -v 'already exists') ; restorecon -R {{ mount_point_dados }}/home"
  register: context_selinux_aplicado
  changed_when: context_selinux_aplicado.rc == 0

- name: Deploy do bash_profile
  copy:
    src: bash_profile.sh
    dest: "{{ novo_home }}/{{ ansible_facts.env.SUDO_USER }}/.bash_profile"
    mode: 0644
    owner: "{{ ansible_facts.env.SUDO_USER }}"
    group: "{{ ansible_facts.env.SUDO_USER }}"
  become: False

- name: Criar diretorio para armazenar instaladores e backups RMAN
  file:
    name: "{{ novo_home }}/{{ ansible_facts.env.SUDO_USER }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_facts.env.SUDO_USER }}"
    group: "{{ ansible_facts.env.SUDO_USER }}"
  become: False
  loop:
    - software
    - backup_rman
...