---
- name: Habilitar EPEL
  package:
    name: epel-release
    state: present

- name: Instalar pacotes
  package:
    name:
      - ansible
      - bind-utils
      - bzip2
      - dnsmasq
      - gcc
      - kernel-devel
      - kernel-headers
      - libguestfs-tools
      - libvirt
      - libvirt-devel
      - make
      - perl
      - policycoreutils-python
      - python3
      - python3-pip
      - qemu
      - qemu-kvm
      - rsync
      - ruby-devel
      - system-config-kickstart
      - telnet
      - tigervnc-server
      - tree
      - unzip
      - wget
      - "@xfce"
    state: present
...