---
- name: Habilitar EPEL
  package:
    name: epel-release
    state: present

- name: Instalar pacotes
  dnf:
    enablerepo: crb
    name:
      - ansible
      - ansible-lint
      - bind-utils
      - bzip2
      - dnsmasq
      - gcc
      - kernel-devel
      - kernel-headers
      - libguestfs-tools
      - libvirt
      - libvirt-devel
      - make
      - perl
      - policycoreutils-python-utils
      - python3
      - python3-pip
      - qemu-kvm
      - rsync
      - ruby-devel
      - telnet
      - tigervnc-server
      - traceroute
      - tree
      - unzip
      - wget
      - "@xfce"
      - "@Virtualization Hypervisor"
      - "@Virtualization Tools"
      - "@Development Tools"
    state: present

- name: Instalar JDK da Oracle
  dnf:
    name: https://download.oracle.com/java/17/archive/jdk-17.0.5_linux-x64_bin.rpm
    state: present
    disable_gpg_check: True
...