---
# Role para criacao de maquina virtual no Google Cloud
# Variaveis esperadas:
#   {{ discos }} - Lista contendo os discos que devem ser criados. Cada disco deve conter os campos nome, tamanho (em GB) e tipo
#   {{ gcp_cred_contents }} - Conteudo do arquivo JSON da conta de servico do Google Cloud
#   {{ gcp_cred_kind }} - Tipo de credencial do Google Cloud
#   {{ gcp_project }} - ID do projeto do Google Cloud
#   {{ ip_interno }} - IP interno a ser usado na maquina
#   {{ network_tier }} - Network Tier da rede a ser criada
#   {{ nome_imagem_so }} - Nome da imagem para o disco de boot
#   {{ nome_ip_externo }} - Nome do recurso do IP externo
#   {{ nome_ip_interno }} - Nome do recurso do IP externo
#   {{ nome_rede_vpc }} - Nome da rede VPC
#   {{ nome_vm }} - Nome da Maquina Virtual
#   {{ region }} - Regiao em que devem ser criados os recursos
#   {{ tipo_maquina }} - Tipo de Maquina Virtual
#   {{ zone }} - Zona em que devem ser criados os recursos

- import_tasks: rede.yml

- import_tasks: discos.yml

- import_tasks: maquina_virtual.yml

- import_tasks: ssh.yml

- name: Adicionar host ao grupo dinamico
  add_host: hostname={{ endereco_ipv4_externo.address }} groupname=novas_instancias
...